// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYgFt2z-qsKAnh2QhJx1G0I-u8Xeczodg',
    appId: '1:246967917143:web:9a9c24dfb6c10fbc94a112',
    messagingSenderId: '246967917143',
    projectId: 'message-app-c5b29',
    authDomain: 'message-app-c5b29.firebaseapp.com',
    storageBucket: 'message-app-c5b29.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeJXweNgTeiVe7hG6HbFOFmFpjuXNEg74',
    appId: '1:246967917143:android:02a4a4570aa100e494a112',
    messagingSenderId: '246967917143',
    projectId: 'message-app-c5b29',
    storageBucket: 'message-app-c5b29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8ljazKJVFkQN5ayhJ7Tf2ndk-HrnmflY',
    appId: '1:246967917143:ios:924831036ee3422d94a112',
    messagingSenderId: '246967917143',
    projectId: 'message-app-c5b29',
    storageBucket: 'message-app-c5b29.firebasestorage.app',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8ljazKJVFkQN5ayhJ7Tf2ndk-HrnmflY',
    appId: '1:246967917143:ios:924831036ee3422d94a112',
    messagingSenderId: '246967917143',
    projectId: 'message-app-c5b29',
    storageBucket: 'message-app-c5b29.firebasestorage.app',
    iosBundleId: 'com.example.messageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYgFt2z-qsKAnh2QhJx1G0I-u8Xeczodg',
    appId: '1:246967917143:web:9acd5d5fb7eeccb794a112',
    messagingSenderId: '246967917143',
    projectId: 'message-app-c5b29',
    authDomain: 'message-app-c5b29.firebaseapp.com',
    storageBucket: 'message-app-c5b29.firebasestorage.app',
  );

}